# Generated by Django 5.2.4 on 2025-07-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The name of the food item (e.g., 'Quinoa').", max_length=200, unique=True)),
                ('calories_per_100g', models.PositiveIntegerField(help_text='The number of calories per 100 grams of the food.')),
            ],
        ),
    ]
