# Generated by Django 5.2.4 on 2025-07-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='calories_per_100g',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='calories',
            field=models.PositiveIntegerField(default=0, help_text='Calories per 100g.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fooditem',
            name='carbs',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Grams of carbohydrates per 100g.', max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fooditem',
            name='fat',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Grams of fat per 100g.', max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fooditem',
            name='fiber',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Grams of fiber per 100g.', max_digits=5),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='image',
            field=models.ImageField(blank=True, help_text='An optional image for the food item.', null=True, upload_to='food_images/'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='protein',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Grams of protein per 100g.', max_digits=5),
            preserve_default=False,
        ),
    ]
