# Generated by Django 5.2.4 on 2025-07-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='goal',
            field=models.CharField(blank=True, choices=[('lose', 'Lose Weight'), ('mobility', 'Mobility / Functionality'), ('gain', 'Gain Weight')], help_text="User's fitness goal.", max_length=10, null=True),
        ),
    ]
